version: "3.3"
services:
  axies-api:
    container_name: axies-api
    restart: always
    image: node:20.10.0
    ports:
      - 5001:4007
    volumes:
      - ./:/usr/src/axies
    working_dir: /usr/src/axies

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"
  axies-batch:
    container_name: axies-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 5002:4008
    volumes:
      - ./:/usr/src/axies
    working_dir: /usr/src/axies

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge




# axies-next: localhost:5000 <==> container: 4000
# axies-api: localhost:5001 <==> container: 4007
# axies-batch: localhost:5002 <==> container: 4008